
[workspace]
resolver = "1"
members = ["core", "seeder"]

[workspace.dependencies]
chrono = {version = "0.4.38", features = ["serde"] }
sqlx = { version = "0.8.2", features = ["runtime-tokio", "chrono", "mysql"] }
tokio = { version = "1.41.1", features = ["full"] }